/* DO NOT EDIT THIS FILE - it is machine generated */
#include <stdio.h>
#include <stdlib.h>
#include <android/log.h>
#include <memory.h>
#include <string.h>
#include "com_example_andrius_ndksampletest_MainActivity.h"
#include "globals.h"
#include "funkcijos.h"



/* Header for class com_example_andrius_ndksampletest_MainActivity */

/*
 * Class:     com_example_andrius_ndksampletest_MainActivity
 * Method:    callNative
 * Signature: ()Ljava/lang/String;
 */

#define  LOG_TAG    "pkcsERR"

#define  LOGE(...)  __android_log_print(ANDROID_LOG_ERROR, LOG_TAG, __VA_ARGS__)


JNIEXPORT jstring JNICALL Java_com_example_andrius_ndksampletest_MainActivity_callNative
  (JNIEnv * env, jobject obj){
  CK_UTF8CHAR_PTR SOpin = "123456";
  CK_UTF8CHAR_PTR userPin = "123456";
    unsigned long ulRet = 0;
  	int op = 0;
  	int i = 0;
  	CK_ULONG i1;
  	char *p = NULL;
  	BOOL  bFlag = FALSE;
  	CK_RV rv;
  	CK_SLOT_ID_PTR pSlotList = NULL;
  	CK_SLOT_ID slotID;
  	CK_ULONG slotCount;

	CK_UTF8CHAR label[] = "My first token";
	CK_ULONG len;

	CK_SLOT_INFO_PTR pSlotInfo = NULL;

	CK_SESSION_HANDLE hSession;

	CK_TOKEN_INFO TokenInfo;


     int test;
     char tev[5] = {"b"};
     test = foo(tev);
  	//	initialize the library
  	rv = C_Initialize (NULL_PTR);
  	if (rv != CKR_OK) {
  		fprintf(STDERR,"***** C_Initialize fails. Error Code: 0x%08x, Line %d\n", rv, __LINE__);
return (*env) -> NewStringUTF(env, "a");
  	} else {
  		fprintf(STDERR,"C_Initialize succeeds.\n" );
//return (*env) -> NewStringUTF(env, "b");
  	}

  	rv = C_GetSlotList (FALSE, NULL_PTR, &slotCount);
  	if (rv != CKR_OK) {
  		fprintf(STDERR, "***** C_GetSlotList fails. Error Code: 0x%08x - Slot Count: %x, Line %d\n", rv, slotCount, __LINE__);
return (*env) -> NewStringUTF(env, "c");
  	}
  	else if (slotCount == 0) {
  		fprintf(STDERR, "***** No slot found!\n");
return (*env) -> NewStringUTF(env, "d");
  	}

	pSlotList = (CK_SLOT_ID_PTR) malloc (slotCount * sizeof(CK_SLOT_ID));
pSlotInfo = (CK_SLOT_INFO_PTR) malloc (slotCount * sizeof(CK_SLOT_INFO));
rv = C_GetSlotList (FALSE, pSlotList, &slotCount);
    if (rv != CKR_OK) {
    	fprintf(STDERR,"***** C_GetSlotList fails. Error Code: 0x%08x - Slot Count: %x, Line %d\n", rv, slotCount, __LINE__);
return (*env) -> NewStringUTF(env, "e");
    }

    printf("There are %d SD Card:\n", slotCount);
    LOGE("There are %d SD Card:\n",slotCount);
//return (*env) -> NewStringUTF(env, "h");
	//char *szFormat = "The sum of the two numbers is: %i";
     //char *szResult;
     for (i1=0; i1 < slotCount; i1++) {
     		slotID = pSlotList[0];
     		LOGE("***** Slot id: %d\n",pSlotList[i]);
     		}


	rv = C_GetTokenInfo(slotID, &TokenInfo);


	if (rv != CKR_OK) {
		fprintf(STDERR,"***** C_GetTokenInfo fails. Error Code: 0x%08x, Line %d\n", rv, __LINE__);
		LOGE("***** C_GetTokenInfo fails. Error Code: 0x%08x\n",rv);
	}
	else {
		fprintf(STDERR,"Token 0x%X Information (CK_TOKEN_INFO):\n", slotID);

		fprintf(STDERR,"   Manufacturer ID = ");
		for(i = 0; i < sizeof(TokenInfo.manufacturerID) / sizeof(CK_UTF8CHAR); ++i)
				LOGE("%c",TokenInfo.manufacturerID[i]);


		fprintf(STDERR,"   Model = ");
		for(i = 0; i < sizeof(TokenInfo.model) / sizeof(CK_UTF8CHAR); ++i)
		LOGE("%c",TokenInfo.model[i]);
		fprintf(STDERR, "\n");

		fprintf(STDERR,"   Serial Number = ");
		for(i = 0; i < sizeof(TokenInfo.serialNumber) / sizeof(CK_CHAR); ++i)
				fprintf(STDERR, "%c", TokenInfo.serialNumber[i]);
		fprintf(STDERR, "\n");

		fprintf(STDERR,"   Flags = 0x%08x (see Table 10, Token Information Flags)\n\n", TokenInfo.flags);
	}











		slotID = pSlotList[0];

		LOGE("Slot id = %d\n",slotID );

		rv = C_GetSlotInfo (slotID,&pSlotInfo[0]);
		if (rv != CKR_OK) {
		//return (*env) -> NewStringUTF(env, "f");
			fprintf(STDERR,"***** C_GetSlotInfo fails. Error Code: 0x%08x, Line %d\n", rv, __LINE__);
			LOGE("***** C_GetSlotInfo fails. Error Code: 0x%08x,",rv);
			LOGE("***** C_GetSlotInfo fails. Line: %d,",__LINE__);
		}
		else {
					//return (*env) -> NewStringUTF(env, "h");
			int n;
        	for(n = 0; n < sizeof(pSlotInfo[0].slotDescription) / sizeof(CK_UTF8CHAR); ++n){
        				LOGE("%c,",pSlotInfo[0].slotDescription[n]);
        }

		}



     	//	int bb = 256;
  // slotID = (CK_SLOT_ID) bb;

len = strlen(SOpin);




	char buf[180]; // assumed large enough to cope with result
	int a;
	int b;
	a = (int) slotCount;
	b = (int) slotID;
	sprintf(buf, "slotu kiekis:%d\n sloto ID: %d\n JNI direct: %s", a,b, tev);
        // get an object string
        //jstring result = (*env)->NewStringUTF(env, "s");


   rv = C_Finalize (NULL_PTR);
   	if (rv != CKR_OK) {
   		fprintf(STDERR,"***** C_GetInfo fails. Error Code: 0x%08x, Line %d\n", rv, __LINE__);
   	} else {
   		fprintf(STDERR,"C_Finalize succeeds.\n" );
   	}



  return (*env) -> NewStringUTF(env, buf);
  }
  JNIEXPORT jstring JNICALL Java_com_example_andrius_ndksampletest_MainActivity_callNative2
    (JNIEnv * env, jobject obj, jstring file){
	const char *inCStr = (*env)->GetStringUTFChars(env, file, NULL);
       if (NULL == inCStr) return NULL;

    return (*env) -> NewStringUTF(env,"gavau" );
   }